# Generated by Django 3.1.3 on 2020-11-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=155, verbose_name='Название модели')),
                ('power', models.DecimalField(decimal_places=15, max_digits=15, verbose_name='Мощность')),
            ],
            options={
                'verbose_name': 'Солнечные панели',
                'verbose_name_plural': 'Солнечныя панель',
            },
        ),
    ]
