# Generated by Django 3.1.3 on 2020-11-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0002_auto_20201111_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarpanel',
            options={'verbose_name': 'Солнечная панель', 'verbose_name_plural': 'Солнечные панели'},
        ),
    ]
