# Generated by Django 3.1.3 on 2020-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0003_auto_20201111_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindTurbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=155, verbose_name='Название модели')),
                ('power', models.DecimalField(decimal_places=15, max_digits=15, verbose_name='Мощность')),
            ],
            options={
                'verbose_name': 'Солнечная панель',
                'verbose_name_plural': 'Солнечные панели',
            },
        ),
    ]
