# Generated by Django 3.1.3 on 2020-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0004_windturbine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название группы')),
                ('slug', models.SlugField(max_length=10, verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Группа зданий',
                'verbose_name_plural': 'Группы зданий',
            },
        ),
    ]
