# Generated by Django 3.1.3 on 2020-11-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0005_buildingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название строения')),
                ('consumption', models.DecimalField(decimal_places=15, max_digits=15, verbose_name='Расход здания на этаж')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTI_srv_neyronka.buildingtype', verbose_name='Группа здания')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
    ]
