# Generated by Django 3.1.3 on 2020-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0006_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='consumption',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='Расход здания на этаж'),
        ),
        migrations.AlterField(
            model_name='windturbine',
            name='power',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='Мощность'),
        ),
    ]
