# Generated by Django 3.1.3 on 2020-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0007_auto_20201113_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windturbine',
            options={'verbose_name': 'Ветряк', 'verbose_name_plural': 'Ветряки'},
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='power',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='Мощность'),
        ),
    ]
