# Generated by Django 3.0.6 on 2020-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0009_auto_20201114_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('std', models.DecimalField(decimal_places=7, max_digits=15, verbose_name='std')),
                ('mean', models.DecimalField(decimal_places=7, max_digits=15, verbose_name='mean')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
