# Generated by Django 3.0.6 on 2020-11-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_y',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=15, verbose_name='max_y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='min_y',
            field=models.DecimalField(decimal_places=7, default=213, max_digits=15, verbose_name='min_y'),
            preserve_default=False,
        ),
    ]
