# Generated by Django 3.0.6 on 2020-11-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0011_auto_20201117_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='max_y',
            field=models.CharField(max_length=155, verbose_name='max_y'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mean',
            field=models.CharField(max_length=155, verbose_name='mean'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='min_y',
            field=models.CharField(max_length=155, verbose_name='min_y'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='std',
            field=models.CharField(max_length=155, verbose_name='std'),
        ),
    ]
