# Generated by Django 3.1.3 on 2020-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0012_auto_20201117_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpanel',
            name='Ko',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Ko'),
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='U',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='U'),
        ),
        migrations.AddField(
            model_name='windturbine',
            name='Ng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Ng'),
        ),
        migrations.AddField(
            model_name='windturbine',
            name='Q',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Q'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_y',
            field=models.CharField(max_length=1551, verbose_name='max_y'),
        ),
    ]
