# Generated by Django 3.1.3 on 2020-11-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0013_auto_20201118_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarpanel',
            name='diameter',
        ),
    ]
