# Generated by Django 3.1.3 on 2020-11-19 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0014_remove_solarpanel_diameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('prectot', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Кол-во осадков')),
                ('qv2m', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Влажность')),
                ('ps', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Давление')),
                ('t2m', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Температура')),
            ],
            options={
                'verbose_name': 'Метеоданные',
                'verbose_name_plural': 'Метеоданные',
            },
        ),
    ]
