# Generated by Django 3.1.3 on 2020-11-19 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0017_auto_20201119_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteodata',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
