# Generated by Django 3.1.3 on 2020-11-21 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NTI_srv_neyronka', '0018_auto_20201119_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('prectot', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Кол-во осадков')),
                ('qv2m', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Влажность')),
                ('ps', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Давление')),
                ('t2m', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Температура')),
            ],
            options={
                'verbose_name': 'Актуальные данные',
                'verbose_name_plural': 'Актуальные данные',
            },
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='prectot',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Кол-во осадков'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='ps',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Давление'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='qv2m',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='t2m',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Температура'),
        ),
    ]
